apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-wallet
type: Opaque
data:
  voter_wallet_json: {{ .Values.secret.voterWalletValue | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-password
type: Opaque
data:
  voter_password: {{ .Values.secret.voterPasswordValue | b64enc | quote }}  