environments:
  ci:
  local:

repositories:
- name: w3f
  url: https://w3f.github.io/helm-charts/

releases:

- name: kusama-voter
  chart: ../charts/polkadot-voter
  values:
  - ./config/watcher-values.yaml.gotmpl
